version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  build:
    docker:
      - image: codeception/codeceptjs
    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
 
          name: "Setup custom environment variables // its your workflow step"
 
          command: 
 
            echo 'export LT_USERNAME="{ggokhankocaman}"' >> $BASH_ENV
 
      - run:
 
          name: "Setup custom environment variables"
 
          command: 
 
            echo 'export LT_ACCESS_KEY="{u4WBqPi8HERIBIZA73hjBv2JY2X3lExjmPz5gUPYGOk6J6Fa8H}"' >> $BASH_ENV
      - run: # Validating your above mentioned environment variables
 
          name: "Here is the LT_Username : "
 
          command: echo ${ggokhankocaman}   

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # we need to install CircleCI CLI tool
      # to run the "manual" tests
      - run: npx codeceptjs run
workflows:
  orb_tests:
    jobs:
      - build